server:
  port: 9091

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3336/first?characterEncoding=UTF-8&useSSL=true&serverTimezone=PRC&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: sckr
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  #时间戳统一转换为指定格式
    time-zone: Asia/Shanghai

jwt:
  secret: ssssaaddd
  expire: 3600
  header: token
